# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:     
    include:
      - none

pool:
  vmImage: ubuntu-latest

jobs:
- job: pre-approval
  pool: server
  steps:
  - task: ManualValidation@0
    inputs:
      notifyUsers: 'tnihar.devops@gmail.com'
      instructions: 'Please approve or reject'


- job: main_job
  dependsOn: pre-approval
  steps:
  - script: echo hello
  displayName: Run a one-line script
